export const {
    NEXT_PUBLIC_URL_GET_EVENTS_CALENDAR,
    NEXT_PUBLIC_URL_GET_EVENTS,
    NEXT_PUBLIC_URL_GET_PRODUCERS,
    NEXT_PUBLIC_URL_GET_TECHNICIAN,
    NEXT_PUBLIC_URL_GET_ASSISTANCE,
    NEXT_PUBLIC_URL_GET_REPORTS,
    NEXT_PUBLIC_MAPBOX_TOKEN,
    NEXT_PUBLIC_AWS_TOKEN,
    EMAIL_CONTACT
} = process.env;